name: Test d2
on: push 
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: test d2 code
        uses: actions/ckeckout@v3
      - name: install independensis 
        run: npm ci 
      - name: test aplications
        run: npm run test
