name: Test d2
on: push 
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: test d2 code
        uses: actions/checkout@v3
      - name: install independensis 
        run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - name: test aplications
        run: d2 --watch in.d2 first_try.svg
